name: xeus-haskell-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - cmake
  - make
  - c-compiler
  - cxx-compiler
  - jupyterlite
  - jupyterlite-xeus
  - emscripten_emscripten-wasm32==3.1.73
