name: CI
on:

  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main

  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  generic:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true
          cache-downloads: true

      - name: Make build directory
        run: mkdir build

      - name: Configure cmake
        shell: bash -l {0}
        run: |
          cmake .. \
           -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
        working-directory: build

      - name: Build & Install
        shell: bash -l {0}
        run: cmake --build . --target install --config Release
        working-directory: build

      - name: Run C++ Test
        shell: bash -l {0}
        run: ctest -C Release --test-dir . --output-on-failure
        working-directory: build

      - name: Run Python Test
        shell: bash -l {0}
        run: pytest . --reruns 5
        working-directory: test


  emscripten_wasm:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.73"]

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-wasm-build.yml
          environment-name: xeus-haskell-wasm-build
          cache-environment: true
          cache-downloads: true

      - name: Build
        shell: bash -l {0}
        run: |
          micromamba create -f environment-wasm-host.yml --platform=emscripten-wasm32

          export EMPACK_PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-haskell-wasm-build
          export PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-haskell-wasm-host
          export CMAKE_PREFIX_PATH=$PREFIX
          export CMAKE_SYSTEM_PREFIX_PATH=$PREFIX
          export BUILD_DIR=/tmp/xeus-haskell-build

          mkdir $BUILD_DIR

          unset CFLAGS CXXFLAGS LDFLAGS

          emcmake cmake \
            -S . \
            -B $BUILD_DIR \
            -DCMAKE_BUILD_TYPE=Release                        \
            -DCMAKE_PREFIX_PATH=$PREFIX                       \
            -DCMAKE_INSTALL_PREFIX=$PREFIX                    \
            -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON

          cmake --build $BUILD_DIR
          cmake --install $BUILD_DIR

